version: '3.8'
services:
  movies-spring:
    image: "movies"
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - movies-db
  movies-db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  pgdata: